name: 'Generate and Publish Doxygen Docs'
description: 'Action to generate and publish Doxygen documentation'
inputs:
  config-file:
    description: 'Path to the Doxyfile'
    required: true
    default: 'Doxyfile'
  token:
    description: 'GitHub token to enable control of github pages'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: Checkout repository
      # uses: actions/checkout@v2

    # - name: Generate documentation
    #   shell: bash
    #   run: |
    #     sudo apt-get install doxygen

    - name: Generate Doxygen documentation
      shell: bash
      run: |
        cd ./docs
        doxygen ${{ inputs.config-file }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
