name: Generate and publish Doxygen documentation

on:
  push:
    branches: [ "master", "mika_dev/documentation" ]
  workflow_dispatch:

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: generate documentation
        uses: ./custom_github_actions/deploy_docs/action.yml
        with: 
          token: ${{ secrets.SAI2_TOKEN }}